### ISSUE TITLE
Sass : Full Exception

### ISSUE THREAD

**Issue by stef-rausch** [penman/SassUnit#2]
In addition to the Issue #1 it would be nice to have the option to :
- **Suppress the detailed error description**, e.g. when the `CSS` file is missing or with a user raised `@error`.

Cheers.

**Comment by alyssais** [comment]
Could you try using the latest version of the gem from GitHub and let me know if it's any better?

```
git clone https://github.com/alyssais/SassUnit.git
cd SassUnit
rake install
```

Use `gem uninstall SassUnit -v 1.0.0` to go back to the old version if something breaks.

**Comment by stef-rausch** [comment]
Nice job @alyssais ! Version `1.0.0` has a cleaner output now :smile: Well done.

There is only one small hiccup — as reported in #1 :
- Running `SassUnit` from the `Terminal` does the job with the following error message :
  
  `fatal: Not a git repository (or any of the parent directories): .git`
- Hence, automating / integrating the running of `SassUnit` does not work anymore — I tried both `Hazel` and `CodeKit`. The fatal error does stop the process and no output is generated.

I assume it's only a small issue that ( hopefully ) can easily be rectified — version `0.0.2` did run fine.

When will version `1.0.1` be available? :wink:
