### ISSUE TITLE
Error when using SassUnit outside of a git repository

### ISSUE THREAD

**Issue by penman** [penman/SassUnit#4]
As reported in #1 by @StefanoRausch:

> - Running `SassUnit` from the `Terminal` does the job with the following error message :

>    `fatal: Not a git repository (or any of the parent directories): .git`

**Comment by stef-rausch** [comment]
Unfortunately not @alyssais, still getting the same `error` message.

**Comment by stef-rausch** [comment]
Did you have the chance to look in to the issue @alyssais ?

**Comment by penman** [comment]
I think this is probably because of an installation issue. Could you try uninstalling every version of gem you have installed using `gem uninstall sassunit`, then clone this repository and run `rake install` from inside the sassunit directory?

**Comment by penman** [comment]
Closing this for now since I'm pretty sure the issue is fixed for new installs.

**Comment by stef-rausch** [comment]
Updated the clone after having uninstalled sassunit. Rake installed the application and the the error message still applies — sorry @alyssais .
