### ISSUE TITLE
Error Testing CSS Files With Several Rules

### ISSUE THREAD

**Issue by StefanoRausch** [penman/SassUnit#6]
Hi @penman,

Hope you are having a good last day of the year and fingers crossed for a better start into the new one :smiley:

I should have read your [introductory article](http://rosspenman.com/testing-sass/) more carefully ... `Sassunit` nearly made me mad, while trying to run a test with the respective `CSS` file containing more than 1 rule — no `Sass` output at all and hence test failure recorded. This looks like to be a Sass issue and not a Sassunit one — I still have to figure out why and will keep you in the loop.

Splitting the big test into tiny ones with only one rule to compare does the trick. Instead of having 4 bigger tests I now have 17 smaller ones :wink: 

The documentation should state that ( very ) clearly — just a hint from my side.

**Comment by penman** [comment]
I think I have an idea why this might be, and I think it's fixable from my side. I'll take a look when I get a chance.

**Comment by StefanoRausch** [comment]
:+1: and thanks.

**Comment by StefanoRausch** [comment]
Hi @penman , did you have time to look into the issue ?

**Comment by penman** [comment]
I'm afraid I can't reproduce this error. Could you give me an example file that's failing due to this?

**Comment by StefanoRausch** [comment]
Will put together a sample file for you to play with.

**Comment by penman** [comment]
@StefanoRausch hey! Did you ever get a sample file together that demonstrates this issue?

**Comment by penman** [comment]
@StefanoRausch ping
